### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by Hector096** [wuyepabdul/leader-board#4]
Hey, you did absolutely amazing work on this project. 🗡️  But there is always a little room for improvement 😵‍💫 

-> It will be good if you, Update your demo link. 
-> (Optional) You can remove the create game after creating the game, It will give a good UX for your app.

Happy Coding!! 🦅

**Comment by wuyepabdul** [comment]
Thanks for the feedback Vishual.
